apiVersion: v1
kind: Service
metadata:
  name: name-of-status-exporter
  namespace: monitoring
  labels:
    app: name-of-status-exporter
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
  selector:
    app: name-of-status-exporter