apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: name-of-status-exporter
    release: prom
  name: name-of-status-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 1m
    port: http
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: name-of-status-exporter